services:
  - type: web
    name: ai-script-grader-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GUNICORN_RUNNING
        value: "true"
      - key: PORT
        value: "10000"
